name: Verso

packages:
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: "2.7.6"
  TelemetryClient:
    url: https://github.com/TelemetryDeck/SwiftClient.git
    from: "2.0.0"

options:
  bundleIdPrefix: com.fabiosasseron
  deploymentTarget:
    iOS: "16.0"

targets:
  Verso:
    type: application
    platform: iOS
    sources:
      - Sources
      - Shared
      - Resources
      - Model
      - path: Resources/readability
        type: folder
        buildPhase: resources
      - path: ../SampleArticles
        type: folder
        buildPhase: resources
    dependencies:
      - package: SwiftSoup
      - package: TelemetryClient
    attributes: {}
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Verso
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIApplicationSupportsIndirectInputEvents: true
        UIRequiresFullScreen: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
        NSUbiquitousContainers:
          iCloud.com.fabiosasseron.verso:
            NSUbiquitousContainerIsDocumentScopePublic: true
            NSUbiquitousContainerName: Verso
            NSUbiquitousContainerSupportedFolderLevels: Any
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fabiosasseron.verso
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
        DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    entitlements:
      path: Resources/Verso.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.fabiosasseron.verso

  ShareExtension:
    type: app-extension
    platform: iOS
    productName: ShareExtension
    bundleId: com.fabiosasseron.verso.ShareExtension
    sources:
      - ShareExtension/Sources
      - Shared
    dependencies:
      - package: SwiftSoup
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fabiosasseron.verso.ShareExtension
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: ShareExtension/Resources/Info.plist
        DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
    entitlements:
      path: ShareExtension/Resources/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.fabiosasseron.verso