name: Verso
options:
  bundleIdPrefix: com.fabiosasseron
  deploymentTarget:
    iOS: "16.0"

targets:
  Verso:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources
    attributes:
      SystemCapabilities:
        com.apple.iCloud:
          enabled: 1
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Verso
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIApplicationSupportsIndirectInputEvents: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
        NSUbiquitousContainers:
          iCloud.com.fabiosasseron.verso:
            NSUbiquitousContainerIsDocumentScopePublic: true
            NSUbiquitousContainerName: Verso
            NSUbiquitousContainerSupportedFolderLevels: Any
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fabiosasseron.verso
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
    entitlements:
      path: Resources/Verso.entitlements
      properties:
        com.apple.developer.icloud-services:
          - CloudDocuments
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.$(CFBundleIdentifier)
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)$(CFBundleIdentifier)